version: '3.7'

services:
  onebox:
    container_name: onebox
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - onebox-network
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - onebox-network
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - onebox-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - onebox-network
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
networks:
  onebox-network:
volumes:
  pgdata: